package flexpg

import (
	"database/sql"
	"errors"
	"fmt"
	"net/url"
	"reflect"
	"strings"
	"sync"

	"git.kanosolution.net/kano/dbflex"

	"git.kanosolution.net/kano/dbflex/drivers/rdbms"
	_ "github.com/lib/pq"
	"github.com/sebarcode/codekit"
)

// Connection implementation of dbflex.IConnection
type Connection struct {
	rdbms.Connection
	db *sql.DB
	tx *sql.Tx

	txIsDisabled bool
	autoValueMu  sync.Mutex
	autoValues   map[string]map[string]interface{}
}

var _ dbflex.IAutoValueConnection = (*Connection)(nil)

func init() {
	dbflex.RegisterDriver("postgres", func(si *dbflex.ServerInfo) dbflex.IConnection {
		c := new(Connection)
		c.SetThis(c)
		c.ServerInfo = *si
		return c
	})
}

// Connect to database instance
func (c *Connection) Connect() error {
	db, err := sql.Open("postgres", c.connectionString())
	if err != nil {
		return err
	}
	db.SetMaxIdleConns(0)
	c.db = db
	return nil
}

func (c *Connection) connectionString() string {
	u := &url.URL{
		Scheme: "postgres",
		Host:   c.Host,
		Path:   "/" + strings.TrimPrefix(c.Database, "/"),
	}
	if c.User != "" {
		u.User = url.UserPassword(c.User, c.Password)
	}

	query := url.Values{}
	sslRoot := ""
	for key, value := range c.Config {
		if strings.EqualFold(strings.TrimSpace(key), "sslroot") {
			sslRoot = fmt.Sprint(value)
			continue
		}
		query.Set(key, fmt.Sprint(value))
	}
	if query.Get("sslrootcert") == "" && sslRoot != "" {
		query.Set("sslrootcert", sslRoot)
	}
	u.RawQuery = query.Encode()
	return u.String()
}

func (c *Connection) State() string {
	if c.db != nil {
		return dbflex.StateConnected
	}
	return dbflex.StateUnknown
}

// Close database connection
func (c *Connection) Close() {
	if c.db != nil {
		c.db.Close()
	}
}

// NewQuery generates new query object to perform query action
func (c *Connection) NewQuery() dbflex.IQuery {
	q := new(Query)
	q.SetThis(q)
	q.conn = c
	return q
}

// GetAutoVal returns and consumes a value captured by INSERT ... RETURNING.
func (c *Connection) GetAutoVal(tableName, fieldName string) (interface{}, error) {
	c.autoValueMu.Lock()
	defer c.autoValueMu.Unlock()

	tableValues, ok := c.autoValues[tableName]
	if !ok {
		return nil, fmt.Errorf("no generated values found for table %s", tableName)
	}
	value, ok := tableValues[fieldName]
	if !ok {
		return nil, fmt.Errorf("generated value for %s.%s was not returned", tableName, fieldName)
	}

	delete(tableValues, fieldName)
	if len(tableValues) == 0 {
		delete(c.autoValues, tableName)
	}
	return value, nil
}

func (c *Connection) setAutoValues(tableName string, fieldNames []string, values []interface{}) {
	c.autoValueMu.Lock()
	defer c.autoValueMu.Unlock()

	if c.autoValues == nil {
		c.autoValues = map[string]map[string]interface{}{}
	}
	tableValues := make(map[string]interface{}, len(fieldNames))
	for idx, fieldName := range fieldNames {
		if idx < len(values) {
			tableValues[fieldName] = values[idx]
		}
	}
	c.autoValues[tableName] = tableValues
}

func (c *Connection) clearAutoValues(tableName string) {
	c.autoValueMu.Lock()
	defer c.autoValueMu.Unlock()
	delete(c.autoValues, tableName)
}

func (c *Connection) DropTable(name string) error {
	cmd := "DROP TABLE " + name
	var e error
	if c.IsTx() {
		_, e = c.tx.Exec(cmd)
	} else {
		_, e = c.db.Exec(cmd)
	}
	return e
}

func (c *Connection) EnsureTable(name string, keys []string, obj interface{}) error {
	var e error
	cmdTxts := []string{}
	if !c.HasTable(name) {
		if cmdTxt, e := createCommandForCreateTable(name, keys, obj); e != nil {
			return e
		} else {
			cmdTxts = append(cmdTxts, cmdTxt)
		}
	} else {
		if cmdTxts, e = createCommandForUpdatingTable(c, name, obj); e != nil {
			return e
		}
		if len(cmdTxts) == 0 {
			return nil
		}
	}

	logger := dbflex.Logger()
	for _, cmdTxt := range cmdTxts {
		logger.Info(cmdTxt)
		if c.IsTx() {
			_, e = c.tx.Exec(cmdTxt)
		} else {
			_, e = c.db.Exec(cmdTxt)
		}
		if e != nil {
			return fmt.Errorf("error: %s command: %s", e.Error(), cmdTxt)
		}
	}

	return nil
}

func createCommandForCreateTable(name string, keys []string, obj interface{}) (string, error) {
	tableCreateCommand := "CREATE TABLE %s (%s);"
	fields := []string{}
	v := reflect.ValueOf(obj)
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == reflect.Struct {
		t := v.Type()
		fnum := t.NumField()
		for i := 0; i < fnum; i++ {
			f := t.Field(i)
			tag := f.Tag
			fieldName := f.Name
			alias := f.Tag.Get(codekit.TagName())
			originalFieldName := fieldName
			if alias == "-" {
				continue
			}
			if alias != "" {
				fieldName = alias
			}

			fieldType := pgFieldType(f)

			options := []string{}
			if f.Tag.Get("db_auto") == "1" && supportsIdentity(fieldType) {
				options = append(options, "GENERATED BY DEFAULT AS IDENTITY")
			}
			if codekit.HasMember(keys, originalFieldName) || codekit.HasMember(keys, fieldName) {
				options = append(options, "PRIMARY KEY")
			}
			if _, ok := tag.Lookup("required"); ok {
				options = append(options, "NOT NULL")
			}
			fields = append(fields, strings.Replace(fmt.Sprintf("%s %s %s",
				strings.ToLower(fieldName),
				fieldType,
				strings.Join(options, " ")),
				"  ", " ", -1))
		}
	} else {
		return "", errors.New("object should be a struct")
	}
	return fmt.Sprintf(tableCreateCommand, name, strings.Join(fields, ", ")), nil
}

func createCommandForUpdatingTable(c dbflex.IConnection, name string, obj interface{}) ([]string, error) {
	// get fields
	name = strings.ToLower(name)
	tableFields := []codekit.M{}
	sql := "select column_name,udt_name,is_nullable as isnull,column_default,is_identity, 0::bool as included from information_schema.columns where table_name='" + name + "' order by ordinal_position"
	e := c.Cursor(dbflex.SQL(sql), nil).Fetchs(&tableFields, 0).Close()
	if e != nil {
		return nil, errors.New("unable to get table meta. " + e.Error())
	}
	return createCommandForUpdatingTableFields(name, obj, tableFields)
}

func createCommandForUpdatingTableFields(name string, obj interface{}, tableFields []codekit.M) ([]string, error) {
	res := []string{}

	// convert fields to map to ease comparison
	mfs := make(map[string]codekit.M, len(tableFields))
	for _, f := range tableFields {
		mfs[strings.ToLower(f.GetString("column_name"))] = f
	}

	tableUpdateCommand := "ALTER TABLE %s %s;"
	fields := []string{}
	v := reflect.ValueOf(obj)
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}

	if v.Kind() != reflect.Struct {
		return res, errors.New("object should be a struct")
	}

	t := v.Type()
	fnum := t.NumField()
	hasChange := false
	identityColumns := []string{}
	for i := 0; i < fnum; i++ {
		f := t.Field(i)
		fieldName := f.Name
		alias := f.Tag.Get(codekit.TagName())
		if alias == "-" {
			continue
		}
		if alias != "" {
			fieldName = alias
		}
		fieldType := pgFieldType(f)
		isAuto := f.Tag.Get("db_auto") == "1"

		// check if field already exist
		old, exist := mfs[strings.ToLower(fieldName)]

		if exist {
			oldUdtName := strings.ToLower(old.GetString("udt_name"))
			if fieldType != oldUdtName {
				hasChange = true
				fields = append(fields, fmt.Sprintf("alter %s type %s", strings.ToLower(fieldName), fieldType))
			}
			if isAuto && supportsIdentity(fieldType) && !hasAutoGeneration(old) {
				hasChange = true
				fields = append(fields, fmt.Sprintf("alter column %s add generated by default as identity", strings.ToLower(fieldName)))
				identityColumns = append(identityColumns, strings.ToLower(fieldName))
			}
			old.Set("included", true)
		} else {
			hasChange = true
			if isAuto && supportsIdentity(fieldType) {
				fields = append(fields, fmt.Sprintf("add %s %s GENERATED BY DEFAULT AS IDENTITY", strings.ToLower(fieldName), fieldType))
				identityColumns = append(identityColumns, strings.ToLower(fieldName))
			} else {
				fields = append(fields, fmt.Sprintf("add %s %s null", strings.ToLower(fieldName), fieldType))
			}
		}
	}

	if !hasChange {
		return res, nil
	}
	res = append(res, fmt.Sprintf(tableUpdateCommand, name, strings.Join(fields, ",\n")))
	for _, column := range identityColumns {
		res = append(res, fmt.Sprintf("SELECT setval(pg_get_serial_sequence('%s', '%s'), COALESCE((SELECT MAX(%s) FROM %s), 1), (SELECT MAX(%s) IS NOT NULL FROM %s))", name, column, column, name, column, name))
	}

	for _, mf := range mfs {
		if !mf.GetBool("included") {
			res = append(res, fmt.Sprintf("alter table %s drop column %s", name, mf.GetString("column_name")))
		}
	}

	return res, nil
}

func pgFieldType(f reflect.StructField) string {
	if dbType := f.Tag.Get("db_type"); dbType != "" {
		return normalizePGFieldType(dbType)
	}

	fieldType := f.Type.String()
	switch {
	case fieldType == "string":
		return "varchar"
	case fieldType == "int16":
		return "int2"
	case fieldType == "int64":
		return "int8"
	case fieldType != "interface{}" && strings.HasPrefix(fieldType, "int"):
		return "int4"
	case strings.Contains(fieldType, "time.Time"):
		return "timestamptz"
	case fieldType == "float32":
		return "numeric (32,8)"
	case fieldType == "float64":
		return "numeric (64,8)"
	case fieldType == "bool":
		return "boolean"
	default:
		return "jsonb"
	}
}

// normalizePGFieldType keeps model tags compatible with PostgreSQL's
// canonical type names returned by information_schema. This lets EnsureTable
// recognize an existing integer column and add its identity generator instead
// of repeatedly attempting a type change.
func normalizePGFieldType(fieldType string) string {
	switch strings.ToLower(strings.TrimSpace(fieldType)) {
	case "smallint", "int2":
		return "int2"
	case "int", "integer", "int4":
		return "int4"
	case "bigint", "int8":
		return "int8"
	default:
		return fieldType
	}
}

func supportsIdentity(fieldType string) bool {
	switch strings.ToLower(strings.TrimSpace(fieldType)) {
	case "smallint", "int2", "integer", "int", "int4", "bigint", "int8":
		return true
	default:
		return false
	}
}

func hasAutoGeneration(field codekit.M) bool {
	if strings.EqualFold(field.GetString("is_identity"), "YES") {
		return true
	}
	return strings.Contains(strings.ToLower(field.GetString("column_default")), "nextval(")
}

func (c *Connection) BeginTx() error {
	if c.IsTx() {
		return errors.New("already in transaction mode. Please commit or rollback first")
	}
	if c.txIsDisabled {
		return errors.New("tx is disabled")
	}
	tx, e := c.db.Begin()
	if e != nil {
		return e
	}
	c.tx = tx
	return nil
}

func (c *Connection) Commit() error {
	if !c.IsTx() {
		return fmt.Errorf("not is transaction mode")
	}
	if e := c.tx.Commit(); e != nil {
		return e
	}
	c.tx = nil
	return nil
}

func (c *Connection) RollBack() error {
	if !c.IsTx() {
		return fmt.Errorf("not is transaction mode")
	}
	if e := c.tx.Rollback(); e != nil {
		return e
	}
	c.tx = nil
	return nil
}

func (c *Connection) SupportTx() bool {
	return true
}

func (c *Connection) DisableTx(disable bool) {
	c.txIsDisabled = disable
}

func (c *Connection) IsTx() bool {
	return c.tx != nil
}

func (c *Connection) Tx() *sql.Tx {
	return c.tx
}

// trigger versioning

func (c *Connection) EnsureIndex(tableName, idxName string, isUnique bool, fields ...string) error {
	indexName := strings.ToLower(fmt.Sprintf("%s_%s", tableName, idxName))

	res := []string{}
	record := codekit.M{}
	cmdGetIndexCount := fmt.Sprintf("SELECT count(*)::int as indexCount FROM pg_indexes WHERE indexname = '%s'", indexName)
	c.Cursor(dbflex.SQL(cmdGetIndexCount), nil).Fetch(&record).Error()
	if record.GetInt("indexcount") == 1 {
		res = append(res, fmt.Sprintf("drop index %s", indexName))
	}

	var (
		jsonbIndex bool
	)

	for idx, field := range fields {
		if strings.Index(field, ".") > 0 {
			fieldParts := strings.Split(field, ".")
			if len(fieldParts) > 1 {
				jsonbIndex = true
			}

			for fpIndex, fp := range fieldParts {
				if fpIndex > 0 {
					fp = fmt.Sprintf("'%s'", fp)
				}

				if fpIndex == len(fieldParts)-2 {
					fieldParts[fpIndex] = fmt.Sprintf("%s->>", fp)
				} else if fpIndex < len(fieldParts)-2 {
					fieldParts[fpIndex] = fmt.Sprintf("%s->", fp)
				} else {
					fieldParts[fpIndex] = fp
				}
			}

			fields[idx] = fmt.Sprintf("(%s) gin_trgm_ops", strings.Join(fieldParts, ""))
		}
	}

	if jsonbIndex {
		tableName = fmt.Sprintf("%s USING gin", tableName)
	}

	if isUnique {
		res = append(res, fmt.Sprintf("create unique index %s on %s (%s)", indexName, tableName, strings.Join(fields, ", ")))
	} else {
		res = append(res, fmt.Sprintf("create index %s on %s (%s)", indexName, tableName, strings.Join(fields, ", ")))
	}

	var e error
	for _, cmdTxt := range res {
		dbflex.Logger().Info(cmdTxt)
		if c.IsTx() {
			_, e = c.tx.Exec(cmdTxt)
		} else {
			_, e = c.db.Exec(cmdTxt)
		}
		if e != nil {
			return fmt.Errorf("error: %s command: %s", e.Error(), cmdTxt)
		}
	}

	return nil
}
