package flexpg

import (
	"strings"
	"testing"

	"github.com/sebarcode/codekit"
)

type ensureTableAutoModel struct {
	ID   int    `json:"id" key:"1" db_type:"int4" db_auto:"1"`
	Code string `json:"code" db_auto:"1"`
}

type ensureTableAutoAliasModel struct {
	ID int `json:"id" key:"1" db_type:"int" db_auto:"1"`
}

type ensureTableCompatibleTypesModel struct {
	Name  string  `json:"name" db_type:"text"`
	Value float64 `json:"value" db_type:"numeric (64,8)"`
}

func TestCreateCommandForCreateTableUsesIdentityForNumericDBAuto(t *testing.T) {
	command, err := createCommandForCreateTable("auto_items", []string{"ID"}, ensureTableAutoModel{})
	if err != nil {
		t.Fatalf("create command failed: %v", err)
	}
	if !strings.Contains(command, "id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY") {
		t.Fatalf("numeric db_auto field should use identity: %s", command)
	}
	if strings.Contains(command, "code varchar GENERATED BY DEFAULT AS IDENTITY") {
		t.Fatalf("non-numeric db_auto field should not use identity: %s", command)
	}
}

func TestUpdatingTableAddsIdentityForNumericDBAuto(t *testing.T) {
	commands, err := createCommandForUpdatingTableFields("auto_items", ensureTableAutoModel{}, []codekit.M{
		codekit.M{}.Set("column_name", "id").Set("udt_name", "int4").Set("is_identity", "NO").Set("column_default", ""),
		codekit.M{}.Set("column_name", "code").Set("udt_name", "varchar").Set("is_identity", "NO").Set("column_default", ""),
	})
	if err != nil {
		t.Fatalf("update command failed: %v", err)
	}
	if len(commands) != 2 || !strings.Contains(commands[0], "alter column id add generated by default as identity") {
		t.Fatalf("numeric db_auto field should gain identity: %#v", commands)
	}
	if !strings.Contains(commands[1], "pg_get_serial_sequence('auto_items', 'id')") {
		t.Fatalf("identity sequence should be synchronized with existing data: %#v", commands)
	}
}

func TestUpdatingTableKeepsExistingSerialDBAuto(t *testing.T) {
	commands, err := createCommandForUpdatingTableFields("auto_items", ensureTableAutoModel{}, []codekit.M{
		codekit.M{}.Set("column_name", "id").Set("udt_name", "int4").Set("is_identity", "NO").Set("column_default", "nextval('auto_items_id_seq'::regclass)"),
		codekit.M{}.Set("column_name", "code").Set("udt_name", "varchar").Set("is_identity", "NO").Set("column_default", ""),
	})
	if err != nil {
		t.Fatalf("update command failed: %v", err)
	}
	if len(commands) != 0 {
		t.Fatalf("serial-backed db_auto field should remain unchanged: %#v", commands)
	}
}

func TestEnsureTableNormalizesIntAliasForAutoNumber(t *testing.T) {
	command, err := createCommandForCreateTable("auto_items", []string{"ID"}, ensureTableAutoAliasModel{})
	if err != nil {
		t.Fatalf("create command failed: %v", err)
	}
	if !strings.Contains(command, "id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY") {
		t.Fatalf("int alias should create an identity column: %s", command)
	}

	commands, err := createCommandForUpdatingTableFields("auto_items", ensureTableAutoAliasModel{}, []codekit.M{
		codekit.M{}.Set("column_name", "id").Set("udt_name", "int4").Set("is_identity", "NO").Set("column_default", ""),
	})
	if err != nil {
		t.Fatalf("update command failed: %v", err)
	}
	if len(commands) != 2 || strings.Contains(commands[0], "alter id type") || !strings.Contains(commands[0], "alter column id add generated by default as identity") {
		t.Fatalf("int alias should add identity without changing its existing int4 type: %#v", commands)
	}
}

func TestUpdatingTableKeepsCompatiblePostgresTypes(t *testing.T) {
	commands, err := createCommandForUpdatingTableFields("compatible_items", ensureTableCompatibleTypesModel{}, []codekit.M{
		codekit.M{}.Set("column_name", "name").Set("udt_name", "varchar").Set("is_identity", "NO").Set("column_default", ""),
		codekit.M{}.Set("column_name", "value").Set("udt_name", "numeric").Set("is_identity", "NO").Set("column_default", ""),
	})
	if err != nil {
		t.Fatalf("update command failed: %v", err)
	}
	if len(commands) != 0 {
		t.Fatalf("compatible PostgreSQL types should not be altered: %#v", commands)
	}
}

func TestPostgresTypeCompatibilityDoesNotHideRealChanges(t *testing.T) {
	if pgTypesEquivalent("text", "int4") {
		t.Fatal("text and int4 must not be treated as equivalent")
	}
	if pgTypesEquivalent("timestamptz", "timestamp") {
		t.Fatal("timestamp with and without time zone must not be treated as equivalent")
	}
}
